name: .NET Core Build Test

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    # use ubuntu for more build minutes
    runs-on: ubuntu-latest
    # use release mode for all steps
    env:
      config: 'Release'

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '6.0.x'  

      # Install project dependencies 
    - name: Install project dependencies
      working-directory: ./TicketSystem
      run: dotnet restore

      # Build project
    - name: Build project
      working-directory: ./TicketSystem
      run: dotnet build
      
      # Install test project dependencies 
    - name:  Install test project dependencies
      working-directory: ./TicketSystemTest
      run: dotnet restore
      
      # Test test project
    - name: Test project
      working-directory: ./TicketSystemTest
      run: dotnet test
